import { StyleSheet } from 'react-native';

export const createNFTsScreenStyles = (theme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.backgroundPrimary,
    padding: 16, // Add padding for floating tab bar
    paddingTop: 20,
    paddingBottom: 10,
  },
  assetsCard: {
    flex: 1,
    backgroundColor: theme.backgroundSecondary,
    borderRadius: 20,
    padding: 25,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    color: theme.contentPrimary,
  },
  menuButton: {
    backgroundColor: theme.backgroundAccent,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
    minWidth: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: theme.backgroundInverse,
    borderRadius: 25,
    padding: 4,
    marginBottom: 40,
  },
  tab: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 20,
    alignItems: 'center',
  },
  activeTab: {
    backgroundColor: theme.backgroundAccent,
  },
  tabText: {
    fontSize: 16,
    fontWeight: '600',
  },
  activeTabText: {
    color: theme.contentInversePrimary,
  },
  inactiveTabText: {
    color: theme.contentSecondary,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
    marginTop: 60,
  },
  emptyIconContainer: {
    position: 'relative',
    marginBottom: 24,
  },
  coinOverlay: {
    position: 'absolute',
    bottom: -8,
    right: -8,
    width: 32,
    height: 32,
    backgroundColor: '#FFD700',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: theme.backgroundPrimary,
  },
  coinText: {
    color: '#000',
    fontSize: 14,
    fontWeight: 'bold',
  },
  emptyTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: theme.contentPrimary,
    marginBottom: 12,
    textAlign: 'center',
  },
  emptySubtitle: {
    fontSize: 16,
    color: theme.contentSecondary,
    textAlign: "center",
    marginBottom: 32,
    lineHeight: 22,
  },
  browseButton: {
    backgroundColor: '#47e299', // Green button
    paddingHorizontal: 32,
    paddingVertical: 16,
    borderRadius: 25,
    alignSelf: 'center',
    minWidth: 200,
    alignItems: 'center',
    justifyContent: 'center',
  },
  browseButtonText: {
    color: '#060d14',
    fontSize: 16,
    fontWeight: "600",
    textAlign: 'center',
    numberOfLines: 1,
  },
  // Dropdown Menu Styles
  dropdownOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1000,
  },
  dropdownMenu: {
    position: 'absolute',
    top: 80,
    right: 16,
    backgroundColor: theme.backgroundSecondary,
    borderRadius: 12,
    paddingVertical: 8,
    minWidth: 150,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    zIndex: 1001,
  },
  dropdownItem: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 8,
    marginHorizontal: 4,
  },
  dropdownItemText: {
    fontSize: 16,
    color: theme.contentPrimary,
    fontWeight: '500',
  },
  // Hide Assets Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  hideAssetsContainer: {
    backgroundColor: theme.backgroundPrimary,
    flex: 1,
    position: 'absolute',
    padding: 16,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1000,
  },
  hideAssestsInnerContainer: {
    flex: 1,
    backgroundColor: theme.backgroundSecondary,
    borderRadius: 20,
    padding: 25,
  },
  hideAssetsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 20,
    paddingTop: 40,
  },
  hideAssetsTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: theme.contentPrimary,
  },
  doneButton: {
    backgroundColor: theme.backgroundAccent,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  doneButtonText: {
    color: theme.contentInversePrimary,
    fontSize: 16,
    fontWeight: '600',
  },
  hideAssetsContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
});
